### ISSUE TITLE
refactor around config history handling

### ISSUE THREAD

**Issue by uu59** [fluent/fluentd-ui#125]

**Comment by rthbound** [comment]
More description, link to file(s)?

**Comment by uu59** [comment]
https://github.com/fluent/fluentd-ui/blob/master/app/models/fluentd/agent/common.rb#L60
https://github.com/fluent/fluentd-ui/tree/master/app/models/fluentd/setting_archive

These code, but we have some plans for extend config history feature such as history diff displaying.
This issue like a TODO comment after that, because we can't see the final file/code structure for now.
Sorry for poor information issue.

**Comment by okkez** [comment]
History diff is displayed.
