### ISSUE TITLE
Implement Editor feature for Edit Config File 

### ISSUE THREAD

**Issue by toru-takahashi** [fluent/fluentd-ui#141]
Editor on Edit Config File doesn't have no text editor feature.
Feature to insert TAB and to select multiple lines, and to color for tags should be more better to editor config file.

**Comment by uu59** [comment]
Probably we can use [CodeMirror](https://github.com/codemirror/codemirror) with custom syntax file for that.

**Comment by uu59** [comment]
@toru-takahashi we've releases v0.3.13 that embedded rich editor as #143
If you have more ideas, problems, etc, feel free to open new issue.
thanks!
