### ISSUE TITLE
Unable to input any words in regex text box at Select File Format

### ISSUE THREAD

**Issue by toru-takahashi** [fluent/fluentd-ui#145]
# Problem Description
When I use Select File Format, fluentd-ui was caused the issue like the following image.
And, I can't type any words in text box.
[![Gyazo](http://i.gyazo.com/022d8bbf27246326bd0b8fb52c736a68.gif)](http://gyazo.com/022d8bbf27246326bd0b8fb52c736a68)

# Environments
- ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
- fluentd 0.10.59
- fluentd-ui 0.3.12

# Reproduce steps
1. Select "Select File Format"
2. Select regep as format
3. Type words quickly in regexp text box

**Comment by uu59** [comment]
Thank you for reporting.
That was fixed at #146, will release later.
