### ISSUE TITLE
Rails 4.2 compatability

### ISSUE THREAD

**Issue by edjames** [fluent/fluentd-ui#161]
Hi

Is anyone working on this right now?

Thanks,
Ed.

**Comment by repeatedly** [comment]
@uu59 How about this? Do you have a plan to update Rails dependency?

**Comment by uu59** [comment]
I think nothing problem to upgrade to 4.2.
But I have no plan to do that because feature enhancement is important than upgrading Rails for now.

Anyway, going Rails 4.2 is welcome :)

**Comment by edjames** [comment]
Great, thanks!
