### ISSUE TITLE
in_tail multi line support

### ISSUE THREAD

**Issue by uu59** [fluent/fluentd-ui#162]
http://docs.fluentd.org/articles/in_tail

Add new UI parts for generate such config.

```
format multiline
format_firstline /^Started/
format1 /Started (?<method>[^ ]+) "(?<path>[^"]+)" for (?<host>[^ ]+) at (?<time>[^ ]+ [^ ]+ [^ ]+)\n/
format2 /Processing by (?<controller>[^\u0023]+)\u0023(?<controller_method>[^ ]+) as (?<format>[^ ]+?)\n/
format3 /(  Parameters: (?<parameters>[^ ]+)\n)?/
format4 /  Rendered (?<template>[^ ]+) within (?<layout>.+) \([\d\.]+ms\)\n/
format5 /Completed (?<code>[^ ]+) [^ ]+ in (?<runtime>[\d\.]+)ms \(Views: (?<view_runtime>[\d\.]+)ms \| ActiveRecord: (?<ar_runtime>[\d\.]+)ms\)/
```

**Comment by uu59** [comment]
@repeatedly I have some questions about fluentd spec for implement that.

- When `format_firstline` and `format1-5` is set (as described this PR).
  `format_firstline` is matched for log file line A, then fluentd try to match A - (A+4) with `format1` - `format5`, right?

- If so, when line A match with `format1`, but line A+1 doesn't match with `format2`.
  fluentd will collect data partially or ignore?
  In other word, given log is like below, what is fluentd's correct behavior?
```
Started GET "/users/123/" for 127.0.0.1 at 2013-06-14 12:00:11 +0900
foo
bar
```

**Comment by repeatedly** [comment]
@uu59 Sorry for the delay.

- Yes. Technically, `format1-5` are combined with multiline regexp in MultilineParser. When log line is matched with `format_firstline`, in_tail passes buffered log lines to MultilineParser.
- Ignore because fluentd doesn't handle log lines partially.

**Comment by uu59** [comment]
thanks! I'll implement it later :+1:

**Comment by repeatedly** [comment]
:+1:
