### ISSUE TITLE
0.0.0.0 bind

### ISSUE THREAD

**Issue by zoneofjin** [fluent/fluentd-ui#176]
I use fluentd-ui-0.3.19

It cannot connect to the fluentd-ui web from the outside. 

only localhost connections are possible

http://localhost:9292

It cannot bind with 0.0.0.0

Please inform us what is configuration file

**Comment by tanaka51** [comment]
Please tell us that starting command and outputs like below:

```
$ ./bin/fluentd-ui start
Puma 2.11.0 starting...
* Min threads: 0, max threads: 16
* Environment: production
* Listening on tcp://0.0.0.0:9292
```

(this is my outputs, this looks bind with 0.0.0.0)

I think that there is suspicious iptables.

**Comment by zoneofjin** [comment]
- OS: Redhat 6
- ruby 2.2.1p85

# fluentd-ui start
Puma 2.11.1 starting...
* Min threads: 0, max threads: 16
* Environment: production
* Listening on tcp://localhost:9292

# netstat -anpt | more
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name
tcp        0      0 0.0.0.0:111                 0.0.0.0:*                   LISTEN      1256/rpcbind
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      1482/sshd
tcp        0      0 127.0.0.1:631               0.0.0.0:*                   LISTEN      1341/cupsd
tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN      1642/master
tcp        0      0 0.0.0.0:48136               0.0.0.0:*                   LISTEN      1300/rpc.statd
tcp        0     64 1.237.186.66:22             1.237.186.2:44728           ESTABLISHED 2721/sshd
tcp        0      0 1.237.186.66:39004          66.241.106.180:80           ESTABLISHED 2696/python
tcp        1      0 1.237.186.66:34332          123.215.198.11:80           CLOSE_WAIT  2339/clock-applet
tcp        0      0 1.237.186.66:40952          54.186.104.15:443           TIME_WAIT   -
tcp        0      0 1.237.186.66:22             1.237.186.2:39214           ESTABLISHED 2557/sshd
tcp        0      0 ::1:9292                    :::*                        LISTEN      2701/ruby /usr/loca
tcp        0      0 :::111                      :::*                        LISTEN      1256/rpcbind
tcp        0      0 :::22                       :::*                        LISTEN      1482/sshd
tcp        0      0 ::1:631                     :::*                        LISTEN      1341/cupsd
tcp        0      0 ::1:25                      :::*                        LISTEN      1642/master
tcp        0      0 :::34432                    :::*                        LISTEN      1300/rpc.statd

**Comment by uu59** [comment]
Ah, I confirmed that.
`rackup` default bind address was changed by this: https://github.com/rack/rack/pull/514 , and we've updated dependencies on latest fluentd-ui release.

We'll provide an option for specify bind soon.

**Comment by yoshihara** [comment]
We fixed this in `v0.3.20` and released just now. Please confirm it.

**Comment by tanaka51** [comment]
@zoneofjin Thank you for reporting this issue!

**Comment by zoneofjin** [comment]
Thank you
