### ISSUE TITLE
Unable to start fluentd on vagrant box

### ISSUE THREAD

**Issue by sachintaware** [fluent/fluentd-ui#196]
<i>Not exactly an issue,but I am not a ruby rails person and did not find any docmentation on getting this to work.</i>

I have setup fluentd on scotch box vagrant image and installed the required dependencies.
After doing 
```
vagrant@scotchbox:/var/www/fluentd-ui$ bundle exec rails s
=> Booting Puma
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.11.1 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000

```

I have setup fluentd-ui in my project directory which is under `/var/www/`.My structure is 

  ```
  /var/www/
         |
         |__fluentd-ui (alongwith my -app directories)
                 |
                 |__all fluentd ui related files
 ```

I tried to access it via ip address using `192.168.10.33/fluentd-ui/` did not work `192.168.10.33:3000` even this did not work. port `9900` (thought this is default) did not work.
<b>I believe I have configured it correctly,but how am I supposed to access it via the browser? </b>

**Comment by uu59** [comment]
You should run fluentd-ui in VM as `bundle exec rails s -b 0.0.0.0` to access from external VM network.

**Comment by sachintaware** [comment]
Thank you @uu59 .that worked,but I have no registered users for this and it asks me to login. Do we need to setup some database too?

**Comment by uu59** [comment]
No, default account is ready out of the box :)

http://docs.fluentd.org/articles/fluentd-ui
> The default account is username=“admin” and password=“changeme”

**Comment by sachintaware** [comment]
Damn,I tried admin and admin! ;) Thank you Sir. @uu59 
Is there any tutorial to deploy fluentd with ui for a production setup? Keeping in mind the security concerns.

**Comment by uu59** [comment]
Using td-agent is a simple and robust way to use production.
fluentd-ui is packed as td-agent-ui in td-agent.
http://docs.treasuredata.com/articles/td-agent

On a security side, however, how do I say..
In general topic, fluentd-ui is rely on account security, no extra builtin protection such as Basic Authentication, TLS, etc.
Account information is encrypted ([salt + stretching](https://github.com/fluent/fluentd-ui/blob/master/app/models/user.rb)) stored in the server as a file.

**Comment by sachintaware** [comment]
Ok.Will keep it in mind while working on the production environment.
Thank you for the guidance.
