### ISSUE TITLE
Change Password To Default

### ISSUE THREAD

**Issue by Spycomb** [fluent/fluentd-ui#205]
Hi Guys, 
i'm pretty new to ruby, and i got stuck at fluend-ui because i forgot my password ( i've change it from 'changeme' ) and my question is how do i reset the fluentd-ui password to default ?

**Comment by repeatedly** [comment]
@uu59 Could you handle this?

**Comment by uu59** [comment]
You can delete `~/.fluentd-ui/core_data/*-user-pwhash.txt" to restore default password authentication.
If you are using td-agent, you can find it under the "/opt/td-agent" directory.

**Comment by Spycomb** [comment]
it works, thank you :D

**Comment by lucas1993ch** [comment]
the absolute path is in /opt/td-agent/data/production-user-pwhash.txt  if you use td-agent
