### ISSUE TITLE
Autostart of fluentd process with fluentd-ui

### ISSUE THREAD

**Issue by stachdude** [fluent/fluentd-ui#206]
Hi,

Is there an easy way to autostart fluentd (or td-agent) with fluentd-ui startup ?

Right now when you start ui even if you supply needed info in 

```
./core_data/production-fluentd.json
```

and fluentd config file you still need to 'click' start in ui. Is there any way to bypass this ?

**Comment by uu59** [comment]
Currently we don't have both autostart fluentd when fluentd-ui started, and start without click.
It will be useful for some situation, but in a production, fluentd and fluentd-ui should be managed separately I think.

**Comment by okkez** [comment]
No response.
