### ISSUE TITLE
Update to rails 5.

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluentd-ui#207]
td-agent 3 uses ruby 2.4 and Rails and activexxx 4 series don't work with ruby 2.4.
We need to update rails to 5 before stable td-agent 3 relase.
Not urgent now.

**Comment by okkez** [comment]
I'm trying to update to Rails 5.

**Comment by okkez** [comment]
I've created #223

**Comment by okkez** [comment]
Merged #223.
