### ISSUE TITLE
fluentd-ui fails to start because of ruby gem 'activesupport'

### ISSUE THREAD

**Issue by fmax** [fluent/fluentd-ui#210]
docker container with:
OS: Ubuntu 16.04 xenial
td-agent 3.0.0-0 amd64

ruby gems:
fluentd (0.14.11)
fluentd-ui (0.4.3)
rails (5.0.1, 4.2.7.1)
activesupport (5.0.1, 4.2.7.1)

output when trying to start fluentd-ui:
/opt/td-agent/embedded/bin/fluentd-ui start
No entry for terminal type "dumb";
using dumb terminal settings.
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:124:in block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError) from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:inblock (2 levels) in class:Numeric'
from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in block (2 levels) in <class:Numeric>' from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:inblock (2 levels) in class:Numeric'
from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in block (2 levels) in <class:Numeric>' from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:inblock (2 levels) in class:Numeric'
from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in block (2 levels) in <class:Numeric>' from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:inblock (2 levels) in class:Numeric'
from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in block (2 levels) in <class:Numeric>' ... 4053 levels... from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:instart'
from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-ui-0.4.3/bin/fluentd-ui:13:in <top (required)>' from /opt/td-agent/embedded/bin/fluentd-ui:22:inload'
from /opt/td-agent/embedded/bin/fluentd-ui:22:in `

**Comment by uu59** [comment]
It is a Ruby 2.4/Rails 4.2.7.1 combination problem as described here: https://github.com/rails/rails/issues/25125

Please consider to downgrade Ruby to 2.3 or wait a Rails 4.2.8 release.

**Comment by fmax** [comment]
thank's for information - rails 4.2.8 is available:
http://weblog.rubyonrails.org/2017/2/10/Rails-4-2-8-rc1-has-been-released/
so i installed this release - the error message has gone, but still fluentd-ui doesn't start.
there is no logfile or error message to stdout.
exit code is 0

i'm no ruby expert - is there a method to debug fluentd-ui?
is there a workaround?

output from CLI:
/opt/td-agent/embedded/bin/fluentd-ui setup
No entry for terminal type "xterm";
using dumb terminal settings.

/opt/td-agent/embedded/bin/fluentd-ui start
No entry for terminal type "xterm";
using dumb terminal settings.

echo $?
0

steps of installation i ran on my virtual-box with OS ubuntu 16 xenial:
curl https://packages.treasuredata.com/GPG-KEY-td-agent | apt-key add -
echo "deb http://packages.treasuredata.com/3/ubuntu/xenial/ xenial contrib" > /etc/apt/sources.list.d/treasure-data.list   && apt-get update   && apt-get install -y td-agent make automake gcc

/opt/td-agent/embedded/bin/gem install rails --version 4.2.8.rc1 --no-document
/opt/td-agent/embedded/bin/gem install fluent-plugin-elasticsearch
/opt/td-agent/embedded/bin/gem install fluent-plugin-concat
/opt/td-agent/embedded/bin/gem install fluentd-ui

list of installed gems:
/opt/td-agent/embedded/bin/gem list --local

*** LOCAL GEMS ***

actionmailer (4.2.8.rc1, 4.2.7.1)
actionpack (4.2.8.rc1, 4.2.7.1)
actionview (4.2.8.rc1, 4.2.7.1)
activejob (4.2.8.rc1, 4.2.7.1)
activemodel (4.2.8.rc1, 4.2.7.1)
activerecord (4.2.8.rc1, 4.2.7.1)
activesupport (4.2.8.rc1, 4.2.7.1)
addressable (2.5.0)
arel (6.0.4)
aws-sdk (2.6.46)
aws-sdk-core (2.6.46)
aws-sdk-resources (2.6.46)
aws-sigv4 (1.0.0)
bigdecimal (default: 1.3.0)
builder (3.2.3)
bundler (1.13.3)
bzip2-ffi (1.0.0)
celluloid (0.15.2)
concurrent-ruby (1.0.4)
cool.io (1.4.5)
did_you_mean (1.1.0)
diff-lcs (1.3)
draper (1.4.0)
elasticsearch (5.0.0, 1.0.18)
elasticsearch-api (5.0.0, 1.0.18)
elasticsearch-transport (5.0.0, 1.0.18)
erubis (2.7.0)
excon (0.54.0)
faraday (0.11.0)
ffi (1.9.17)
fluent-logger (0.6.2)
fluent-mixin-config-placeholders (0.4.0)
fluent-mixin-plaintextformatter (0.2.6)
fluent-plugin-concat (2.0.1)
fluent-plugin-elasticsearch (1.9.2)
fluent-plugin-kafka (0.5.0)
fluent-plugin-rewrite-tag-filter (1.5.5)
fluent-plugin-s3 (1.0.0.rc1)
fluent-plugin-td (0.10.29)
fluent-plugin-td-monitoring (0.2.2)
fluent-plugin-webhdfs (0.4.2)
fluentd (0.14.11)
fluentd-ui (0.4.3)
font-awesome-rails (4.7.0.1)
globalid (0.3.7)
haml (4.0.7)
haml-rails (0.5.3)
hike (1.2.3)
hirb (0.7.3)
http_parser.rb (0.6.0)
httpclient (2.8.2.4)
i18n (0.8.0)
io-console (default: 0.4.6)
ipaddress (0.8.3)
jbuilder (2.6.1)
jmespath (1.3.1)
jquery-rails (3.1.4)
json (default: 2.0.2, 1.8.6)
kramdown (1.13.2)
kramdown-haml (0.0.3)
loofah (2.0.3)
ltsv (0.1.0)
mail (2.6.4)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.1.0)
minitest (5.10.1)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7)
msgpack (1.0.2)
multi_json (1.12.1)
multipart-post (2.0.0)
net-telnet (0.1.1)
nokogiri (1.7.0.1)
ohai (6.20.0)
oj (2.18.0)
openssl (default: 2.0.2)
parallel (1.8.0)
power_assert (0.4.1)
psych (default: 2.2.2)
public_suffix (2.0.5)
puma (3.7.0)
rack (1.6.5)
rack-test (0.6.3)
rails (4.2.8.rc1, 4.2.7.1)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.8)
rails-html-sanitizer (1.0.3)
railties (4.2.8.rc1, 4.2.7.1)
rake (12.0.0)
rdoc (default: 5.0.0)
request_store (1.3.2)
ruby-kafka (0.3.16.beta2)
ruby-progressbar (1.8.1)
rubyzip (1.1.7)
sass (3.2.19)
sass-rails (4.0.5)
serverengine (2.0.4)
settingslogic (2.0.9)
sigdump (0.2.4)
sprockets (3.7.1, 2.12.4)
sprockets-rails (3.2.0, 2.3.3)
strptime (0.1.9)
sucker_punch (1.0.5)
systemu (2.5.2)
td (0.15.2)
td-client (0.8.85)
td-logger (0.3.26)
test-unit (3.2.3)
thor (0.19.4)
thread_safe (0.3.5)
tilt (1.4.1)
timers (1.1.0)
tzinfo (1.2.2)
tzinfo-data (1.2016.10)
uuidtools (2.1.5)
webhdfs (0.8.0)
xmlrpc (0.2.1)
yajl-ruby (1.3.0)
zip-zip (0.3)

**Comment by uu59** [comment]
Hmm. Perhaps fluentd-ui is using 4.2.7.1 instead of 4.2.8.rc1 because 4.2.8 is still RC state.
bundler (the dependency manager) ignore that version is reasonable.

**Comment by fmax** [comment]
rails 4.2.8 got released - https://rubygems.org/gems/rails/versions/4.2.8
I installed this version and uninstalled rc1 version
but sadly still fluentd-ui wont start :(

/opt/td-agent/embedded/bin/gem list --local | egrep "action|active|rail|fluent"
actionmailer (4.2.8)
actionpack (4.2.8)
actionview (4.2.8)
activejob (4.2.8)
activemodel (4.2.8)
activerecord (4.2.8)
activesupport (4.2.8)
fluent-logger (0.6.2)
fluent-mixin-config-placeholders (0.4.0)
fluent-mixin-plaintextformatter (0.2.6)
fluent-plugin-concat (2.0.1)
fluent-plugin-elasticsearch (1.9.2)
fluent-plugin-kafka (0.5.0)
fluent-plugin-rewrite (0.1.0)
fluent-plugin-rewrite-tag-filter (1.5.5)
fluent-plugin-s3 (1.0.0.rc1)
fluent-plugin-td (0.10.29)
fluent-plugin-td-monitoring (0.2.2)
fluent-plugin-webhdfs (0.4.2)
fluentd (0.14.13)
fluentd-ui (0.4.3)
font-awesome-rails (4.7.0.1)
haml-rails (0.5.3)
jquery-rails (3.1.4)
rails (4.2.8)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (2.0.2, 1.0.8)
rails-html-sanitizer (1.0.3)
railties (4.2.8)
sass-rails (4.0.5)
sprockets-rails (2.3.3)

/opt/td-agent/embedded/bin/fluentd-ui start
No entry for terminal type "dumb";
using dumb terminal settings.
root@49f415f8d3f5:/# echo $?
0
root@49f415f8d3f5:/#

so why fluentd-ui wont start?
any ideas?
how to debug?
some gems needed but required missing?

**Comment by uu59** [comment]
Hmm. I can start fluentd-ui with Rails 4.2.8.

Could you check your log file located log/production.log?

**Comment by fmax** [comment]
sorry, but there isn't any logfile.
my installation for docker container:
* Ubuntu 16.04 LTS
* td-agent 3.0.0-0 amd64
* /opt/td-agent/embedded/bin/gem install fluentd-ui
* /opt/td-agent/embedded/bin/gem install rails --version 4.2.8

/opt/td-agent/embedded/bin/gem list --local | grep -i "fluent"
fluent-logger (0.6.2)
fluent-mixin-config-placeholders (0.4.0)
fluent-mixin-plaintextformatter (0.2.6)
fluent-plugin-concat (2.0.1)
fluent-plugin-elasticsearch (1.9.2)
fluent-plugin-fields-parser (0.1.1)
fluent-plugin-grok-parser (2.1.2)
fluent-plugin-kafka (0.5.0)
fluent-plugin-rewrite (0.1.0)
fluent-plugin-rewrite-tag-filter (1.5.5)
fluent-plugin-s3 (1.0.0.rc1)
fluent-plugin-td (0.10.29)
fluent-plugin-td-monitoring (0.2.2)
fluent-plugin-webhdfs (0.4.2)
fluentd (0.14.13)
fluentd-ui (0.4.3)

/opt/td-agent/embedded/bin/fluentd-ui start --no-daemonize
No entry for terminal type "dumb";
using dumb terminal settings.
root@49f415f8d3f5:/# echo $?
0

how to debug?
which td-agent and which ruby gems in what versions you have installed?

**Comment by nancykyo** [comment]
run into same situation here, any updates?

**Comment by okkez** [comment]
Outdated.

**Comment by LeoWare** [comment]
This is still a thing in the current version of Fluentd-UI with Ruby 3 on Ubuntu 20.04
