### ISSUE TITLE
td_agent_ui_ruby: not found

### ISSUE THREAD

**Issue by 899** [fluent/fluentd-ui#217]
ubuntu 16.04.3 LTS xenial
/usr/sbin/td-agent-ui: 11: /usr/sbin/td-agent-ui: /opt/td-agent/embedded/bin/td_agent_ui_ruby: not found

**Comment by piotrkochan** [comment]
same here

**Comment by EdwinExtendas** [comment]
same here

**Comment by piotrkochan** [comment]
No one cares?

**Comment by okkez** [comment]
Do you use td-agent 2.x? Right?
Please report the issue to https://github.com/treasure-data/omnibus-td-agent

I could not confirm the issue with td-agent_2.5.0-0_amd64.deb.

BTW, this is not fluentd-ui issue. Closing.
